[package]
name = "soda_test"
version = "0.1.0"
edition = "2021"

[dependencies]
soda_core = { path = "../soda_core" }
memory_repository = { path = "../memory_repository" }

[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }